Audit log UI
greenriver/boston-cas pull request #398
Opened 2021-01-15 18:02 UTC by tquang1708

[https://www.pivotaltracker.com/story/show/176485717]

2021-01-19 14:09 UTC, eanders commented
![Screen Shot 2021-01-19 at 9 01 22 AM](https://user-images.githubusercontent.com/1346876/105044694-0646c580-5a35-11eb-9d1d-b74d4444fecb.png)
The Audit button should only show if the permission has been granted.
![Screen Shot 2021-01-19 at 9 01 12 AM](https://user-images.githubusercontent.com/1346876/105044729-11015a80-5a35-11eb-9f0e-74e55243cf65.png)

Types aren't showing up in the log.  Let's remove that column.
![Screen Shot 2021-01-19 at 9 01 43 AM](https://user-images.githubusercontent.com/1346876/105044746-165ea500-5a35-11eb-99c5-37a2fac17819.png)

2021-01-19 14:20 UTC, eanders commented on app/views/admin/audits/_user_tabs.haml
> +  -#   = link_to 'Login Locations', admin_user_locations_path(@user), class: 'nav-link'
Let's go ahead and bring this code over too so we can see who edited the user and where the user logged in from.

2021-01-19 15:01 UTC, tquang1708 commented
On HMIS the audit button still shows regardless of permission. Should I update that on HMIS too?

2021-01-19 15:03 UTC, eanders commented
Sure, just open a new pull request.  Thanks!

> On Jan 19, 2021, at 10:02 AM, Quang Tran <notifications@github.com> wrote:
> 
> 
> On HMIS the audit button still shows regardless of permission. Should I update that on HMIS too?
> 
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub <https://github.com/greenriver/boston-cas/pull/398#issuecomment-762898107>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAKI2PH4CCGT6JMGTT2H373S2WNGRANCNFSM4WENBN7Q>.
>

2021-01-19 23:34 UTC, eanders requested changes
It looks like geocoding isn't working quite correctly.  The warehouse has an additional initializer that may be all it needs. 
`config/initializers/geocode_lite.rb`

If you login and run a delayed job worker, you should see city, region, country data populate in the `login_activities` table.

Also, we should expose the login information as we do in the warehouse under the Edit User pages:
https://qa-warehouse.openpath.host/account/locations

Otherwise, I think this looks great!

2021-01-20 15:12 UTC, tquang1708 commented
I was able to see the delayed worker do something in regards to the `geocode_lite` initializer, though I'm not sure what that changed (the ip address recorded on my machine is a private IP address). In any case, that seem to be working. I managed to expose the login history information too, so if the geocoding is working as intended then we should be in a good position.

2021-01-20 16:22 UTC, merged